### ISSUE TITLE
Poweroff doesn't actually power off

### ISSUE THREAD

**Issue by GXTX** [Ryzee119/Xenium-Tools#2]
On my system it just did a warm reboot into the current kernel, "power off" imo would be a full power off :P

**Comment by Ryzee119** [comment]
Same thing on mine. Ill prob add a reboot option to the menu and fix the power off option.

**Comment by Ryzee119** [comment]
![image](https://user-images.githubusercontent.com/21236406/104169380-6515a900-544f-11eb-86f2-57dc2bf66b14.png)
An exit button has been added. 
Power off now actually powers off :)

**Comment by GXTX** [comment]
Cheers thanks :)
