### ISSUE TITLE
Xenium not detected with Genuine Xenium Ice

### ISSUE THREAD

**Issue by dtomcat** [Ryzee119/Xenium-Tools#6]
I loaded the Xenium Tools with my Xenium Ice (on 2.2.1) and it seen it fine and everything functioned fine.  I updated the chip to 2.3.1, and now it shows "Xenium not detected."  Of note, Xenium-fw-update (by MakeMhz i believe) also now shows "Xenium not detected"  I believe this to be a genuine chip thing since i seen a post of another Xenium Ice chip with same behavior.

TLDR;
Xenium Ice (2.2.1) = OK
Xenium Ice (2.3.1) = "Xenium not found"
xbox = 1.6

**Comment by Ryzee119** [comment]
Xenium-tools detection method is extremely simple. It just checks that the Flash chip has the appropriate flash IDs, so  nothing a software update should impact.

Are you certain your xbox is booting from the chip and not TSOP memory?

**Comment by dtomcat** [comment]
I am 99% sure.  nothing changed from the time I initially ran it on 2.2.1 and 2.3.1 other than update the firmware to 2.3.1.  it did detect it on 2.2.1.  I also just downloaded EvoX and the Yoshihiro-m8-1.6B-Memory-fixe-beta4.bin to booted to both of those and both times it shows Xenium not detected?  not sure what else to try.  I've tried factory reset the chip and that doesn't help.
Thanks for the help and the reply

**Comment by dtomcat** [comment]
Also of note... changing the LED color works... and if I "Write XeniumOS 2.3.1 Update File", after it completes.. the chip is detected.  exiting after causes the recovery mode (is that normal?)

**Comment by dtomcat** [comment]
![CB40FB30-A94D-4449-9658-246A2171D4BD](https://user-images.githubusercontent.com/1297922/171343656-e7ad2176-c72f-4aea-97f3-79855f83dd5b.jpeg)

I tried your original release and it detects the chip?

**Comment by Ryzee119** [comment]
well that is interesting. thanks for the update! Wonder what I changed 🤔

**Comment by dtomcat** [comment]
I believe the issue was with the way Xenium had you build the LPC header back in the day (2x6).  All of the OpenXeniums worked like a charm.  Closing this as this would probably work on an xbox < 1.6.
